services:
  web:
    container_name: fastapi_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  redis:
    container_name: fastapi_redis
    image: redis:7.2  
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  celery_worker:
    container_name: worker
    build: ./
    command: celery --app src.celery_app.app worker --pool threads --loglevel INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  celery_flower:
    container_name: flower
    image: mher/flower:0.9.7
    command: flower --broker=redis://redis:6379/0 --port=5555
    environment:
      - FLOWER_BASIC_AUTH=admin:admin  # Опционально: простая аутентификация
    ports:
      - "5556:5555"
    depends_on:
      - redis
      - celery_worker

volumes:
  redis-data:


